title: Joseph # name of the site
author: Joseph Trevorrow # name of site's author
email: joseph.trevorrow@gmail.com # email of site's author
url: https://josephtrevorrow.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if your site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  <p> <br>Joseph Trevorrow <br> I'm an PhD student at the University of Bristol. <br> I have experience in HPC (Using C type languages), Python for RL, as well as a love for writing, technical analysis and research. <br> Research Interests: Multi-Agent Systems, Value Alignment, Civic AI, Sociotechnical Systems, Computational Ethics, AI and Public/Industrial Policy, Sociology, Ideology, Voting Theory </p>

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
