title: Joseph Trevorrow # name of the site
author: Joseph Trevorrow # name of site's author
email: joseph.trevorrow@gmail.com # email of site's author
url: https://josephtrevorrow.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if your site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  <p> I'm an PhD student at the University of Bristol Interactive AI Centre for Doctoral Training (CDT), supervised by Dr Nirav Ajmeri and Dr Emmanuele Ratti. I'm a part of the Social AI Lab at the University of Bristol.
  <br> <br> 
  My work is centred on value aligned collective decision making for multi-agent systems. I'm interested in creating group decision making methods that are autonomous, flexible to context, robust to risk, and value-aligned.
  <br><br>
  I have experience in Python for Reinforcement Learning and Agent Based Modelling, HPC using Julia and C type languages, as well as a love for writing, technical analysis and research. 
  <br> <br> 
  Research Interests: Multi-Agent Systems, Sociotechnical Systems, AI and Public/Industrial Policy
  </p>


# Notes/News/Updates Section, if it ever becomes something I wish to add. Even so, I may only include times I have presented/published
# April 2025 - I presented my work at the CCAIS Seminar Series as part of a spotlight talk on the Social AI Lab
# April 2025 - I presented my work on Hierarchical Consensus Value Aggregation as part of the University of Bristol CDT Spring Conference.


permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

